config/routes.rb
Rails.application.routes.draw do
  resources :dummies
  root "dummies#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  mount ActionCable.server => "/cable"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dummy.rb
class Dummy < ApplicationRecord
  extend Enumerize

  enumerize :status, in: [ :user, :admin, :idiot ], default: :user

  validates :name, presence: true

  def to_s
    name
  end

  def self.ransackable_attributes(auth_object = nil)
    [ "active", "completed_at", "created_at", "id", "name", "started_at", "status", "updated_at", "date_range" ]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :find_resource, only: %i[edit show update destroy]
  before_action :find_filters_count, only: %i[index]

  def index
    @q = resource_class.ransack(params[:q])
    @pagy, @resources = pagy(@q.result(distinct: true))
    instance_variable_set("@#{controller_name}", @resources)
  end

  def new
    instance_variable_set("@#{resource_name}", resource_class.new)
  end

  def edit; end

  def show; end

  private

  def resource_name
    resource_class.model_name.element
  end

  def resource_class
    raise NotImplementedError, "Please define #resource_class in #{self.class.name}"
  end

  def find_resource
    instance_variable_set("@#{resource_name}", resource_class.find(params[:id]))
  end

  def find_filters_count
    return @filter_count = 0 if params[:q].blank?

    permitted_params = params.require(:q).permit(filterable_attributes)
    @filter_count = permitted_params.to_h.reject { |_, value| value.blank? }.count
  end

  # Define the filterable attributes for Ransack
  def filterable_attributes
    []
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/dummies_controller.rb
class DummiesController < BaseController
  def create
    @dummy = Dummy.new(dummy_params)

    if @dummy.save
      respond_to do |format|
        format.html { redirect_to dummies_path, notice: "Dummy created successfully" }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @dummy.update(dummy_params)
      respond_to do |format|
        # format.html { redirect_to dummies_path }
        format.turbo_stream
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @dummy.destroy
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  # Define the filterable attributes for Ransack in the context of Dummies
  def filterable_attributes
    %i[name_cont status_eq active_eq date_range]
  end

  def dummy_params
    params.require(:dummy).permit(:name, :started_at, :completed_at, :active, :status)
  end

  def resource_class
    Dummy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def date_range_filter(form, start_field:, end_field:, placeholder: "Select date range")
    date_range_value = ""

    if params[:q].present? && params[:q][start_field].present? && params[:q][end_field].present?
      date_range_value = "#{params[:q][start_field]} to #{params[:q][end_field]}"
    end

    content_tag(:div, data: { controller: "date-range" }) do
      form.text_field(:date_range, placeholder: placeholder, value: date_range_value, data: { date_range_target: "visibleInput" }, class: "input input-bordered w-full") +
      form.hidden_field(start_field, value: params.dig(:q, start_field), data: { date_range_target: "startDate" }) +
      form.hidden_field(end_field, value: params.dig(:q, end_field), data: { date_range_target: "endDate" })
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/dummies_helper.rb
module DummiesHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

<%= render Cards::CardComponent.new(as: :primary, title: 'Card Title') do |card| %>
  <% card.with_body_content do %>
    <p>This is my custom card description</p>
  <% end %>
  <% card.with_actions do %>
    <%= render Elements::ButtonComponent.new(title: "Buy now", as: :secondary, size: :md, outline: true) %>
  <% end %>
<% end %>

<%= render Cards::CardComponent.new(as: :secondary, title: 'Pero') do |card| %>
  <% card.with_body_content do %>
    <p>Pero description</p>
  <% end %>
<% end %>

<%= render Cards::CardComponent.new(title: 'Basic card') do |card| %>
  <% card.with_actions do %>
    <button class="btn btn-ghost">Basic btn</button>
  <% end %>
<% end %>

<label class="form-control w-full max-w-xs">
  <div class="label">
    <span class="label-text">What is your name?</span>
  </div>
  <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs" />
</label>

<label class="form-control w-full max-w-xs">
  <div class="label">
    <span class="label-text">What is your name?</span>
  </div>
  <input type="text" placeholder="Type here" class="input input-bordered w-full max-w-xs" />
</label>

app/views/dummies/_dummy.html.erb
<%= render Cards::DummyComponent.new(dummy: dummy) %>

app/views/dummies/_form.html.erb
<%= render Cards::DummyFormComponent.new(dummy: @dummy) %>

app/views/dummies/create.turbo_stream.erb
<% if @dummy.errors.blank? %>
  <%= turbo_stream.append("dummies_list", partial: "dummies/dummy", locals: { dummy: @dummy }) %>
  <%= turbo_stream.replace("new_dummy_form", partial: "shared/empty") %>
<% end %>

app/views/dummies/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@dummy) %>
<%= turbo_stream.replace "flash_messages" do %>
  <%= render Elements::ToastComponent.new(message: "Dummy was successfully deleted.", status: 'notice') %>
<% end %>

app/views/dummies/edit.html.erb
<h1 class="page-title">Edit Dummy</h1>

<%= turbo_frame_tag dom_id(@dummy) do %>
  <%= render 'form' %>
<% end %>

app/views/dummies/index.html.erb
<!-- Page Title -->
<h1 class="page-title">Dummies List</h1>
<p class="page-subtitle">Browse the list of dummies below, or create a new one.</p>

<!-- New Button -->
<div class="flex justify-end mb-6">
  <%= link_to "New Dummy", new_dummy_path, class: "btn btn-primary", data: { turbo_frame: 'new_dummy_form' } %>
</div>

<div class="grid grid-cols-1 md:grid-cols-1 lg:grid-cols-1 gap-2">
  <%= turbo_frame_tag 'new_dummy_form' %>
</div>

 <%= render Shared::SearchFormComponent.new(
  form: @q,
  search_path: dummies_path,
  main_filter: { field: :name_cont, label: "Name", placeholder: "Search by name" },
  additional_filters: [
    { type: :date_range, label: "Date Range", start_field: :started_at_gteq, end_field: :started_at_lteq },
    { type: :select, field: :status_eq, label: "Status", options: Dummy.status.values.map { |status| [status.text, status.value] }, include_blank: "All Statuses" },
    { type: :boolean, field: :active_eq, label: "Active?" }
  ]
) %>

<!-- Dummy Items -->
<%= turbo_frame_tag "results" do %>
  <div class="flex justify-end mb-2 me-2">
    <%== pagy_info(@pagy) %>
    <span class="text-sm text-gray-500 ml-1">with <%= @filter_count %> <%= 'filter'.pluralize(@filter_count) %> applied</span>      
  </div>
  <div class="card bg-white dark:bg-gray-800 shadow-lg rounded-sm w-full mb-2">
  <div class="card-body p-2">
    <div class="grid grid-cols-6 gap-4 text-sm text-gray-900 dark:text-gray-200 items-center">
      <div><%= sort_link(@q, :name, Dummy.human_attribute_name(:name)) %></div>
      <div><%= sort_link(@q, :started_at, Dummy.human_attribute_name(:started_at)) %></div>
      <div><%= Dummy.human_attribute_name(:completed_at) %></div>
      <div><%= sort_link(@q, :active, Dummy.human_attribute_name(:active)) %></div>
      <div><%= sort_link(@q, :status, Dummy.human_attribute_name(:status)) %></div>
    </div>
  </div>
</div>
  <div class="grid grid-cols-1 md:grid-cols-1 lg:grid-cols-1 gap-2" id="dummies_list">
    <%= render @dummies %>
  </div>
  <div class="flex justify-center mt-8">
    <%== pagy_nav(@pagy) %>
  </div>
<% end %>

app/views/dummies/new.html.erb
<%= turbo_frame_tag "new_dummy_form" do %>
  <div data-controller="edit">
    <div data-edit-target="form">
      <h1 class="page-title">New Dummy</h1>    
        <%= render Cards::DummyFormComponent.new(dummy: @dummy) %>    
    </div>
  </div>
<% end %>

app/views/dummies/show.html.erb
<%= render Cards::DummyComponent.new(dummy: @dummy, layout: :compact) %>

app/views/dummies/update.turbo_stream.erb
<% if @dummy.errors.empty? %>
  <%= turbo_stream.replace dom_id(@dummy) do %>
    <%= render Cards::DummyComponent.new(dummy: @dummy) %>
  <% end %>
  <%= turbo_stream.replace "flash_messages" do %>
    <%= render Elements::ToastComponent.new(message: "Dummy was successfully updated.", status: 'notice') %>
  <% end %>
<% else %>
  <%= turbo_stream.replace dom_id(@dummy) do %>
    <%= render partial: 'form' %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Flyui" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <div class="drawer">
  <input id="my-drawer-3" type="checkbox" class="drawer-toggle" />
  <div class="drawer-content flex flex-col">
    <!-- Navbar -->
    <div class="navbar bg-base-300 w-full">
      <div class="flex-none lg:hidden">
        <label for="my-drawer-3" aria-label="open sidebar" class="btn btn-square btn-ghost">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            class="inline-block h-6 w-6 stroke-current">
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </label>
      </div>
      <div class="mx-2 flex-1 px-2">Navbar Title</div>
      <div class="hidden flex-none lg:block">
        <ul class="menu menu-horizontal">
          <!-- Navbar menu content here -->
          <li><a>Navbar Item 1</a></li>
          <li><a>Navbar Item 2</a></li>
        </ul>
      </div>
    </div>
    <!-- Page content here -->
    <main class="container mx-auto mx-2 p-2">
      <%= render "shared/confirm_dialog" %>
      <%= turbo_frame_tag "flash_messages" do %>
        <% flash.each do |type, message| %>
          <%= render Elements::ToastComponent.new(message: message, status: type) %>
        <% end %>
      <% end %>
      
      <%= yield %>
    </main>
  </div>
  <div class="drawer-side">
    <label for="my-drawer-3" aria-label="close sidebar" class="drawer-overlay"></label>
    <ul class="menu bg-base-200 min-h-full w-80 p-4">
      <!-- Sidebar content here -->
      <li><a>Sidebar Item 1</a></li>
      <li><a>Sidebar Item 2</a></li>
    </ul>
  </div>
</div>

    
  </body>
</html>

app/views/shared/_confirm_dialog.html.erb
<!-- not visible without an [open] attribute, which **Turbo-Confirm** will handle for you -->
<dialog id="confirm" class="modal">
  <div class="modal-box modal__content">
    <h3 id="confirm-title" class="font-bold text-lg">Hello!</h3>
    <div id="confirm-body">
      <p>Default confirm message.</p>
      <p>Optionally replaced by `data-confirm-details` attribute</p>
    </div>
    <div class="modal-actions modal-action">
      <button class="confirm-cancel btn btn-error">Cancel</button>
      <button id="confirm-accept" class="btn btn-success">Yes, I'm Sure</button>
    </div>
  </div>
</dialog>